apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels: # these labels are deployment labels
    app: catalogue
    project: roboshop
    tier: app
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "roboshop-dev.czn6yzxlcsiv.us-east-1.rds.amazonaws.com"
